python run_ner.py \
 --model_name_or_path hfl/chinese-roberta-wwm-ext-large \
 --dataset_name gyr66/privacy_detection \
 --validation_split_ratio 0.2 \
 --preprocessing_num_workers 16 \
 --dataloader_num_workers 16 \
 --pad_to_max_length \
 --max_seq_length 512 \
 --use_crf_head \
 --label_all_tokens \
 --output_dir /mnt/ds3lab-scratch/yirguo/saved_models/chinese-roberta-wwm-ext-large-crf-finetuned-ner \
 --num_train_epochs 10 \
 --per_device_train_batch_size 2 \
 --per_device_eval_batch_size 2 \
 --logging_strategy epoch \
 --save_strategy epoch \
 --evaluation_strategy epoch \
 --load_best_model_at_end \
 --metric_for_best_model f1 \
 --do_train --do_eval \
 --report_to none \
 --push_to_hub